version: '2'
services:
  rails_nginx:
    image: nginx:1.13.8-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${PWD}/.ssl:/etc/nginx/ssl:ro
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    volumes_from:
      - rails_app
    depends_on:
      - rails_app
    links:
      - rails_app

  rails_db:
    image: mariadb:10.2.13
    volumes:
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
      - ${PWD}/docker/mariadb/conf.d:/etc/mysql/conf.d:ro
      - ${PWD}/docker/mariadb/init:/docker-entrypoint-initdb.d:ro
      - rails-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3333:3306"

  rails_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        app_dir: ./src
    environment:
      SECRET_KEY_BASE: 988f8ed353b8efb28ad7a7ba1311de92f8ef8d0e3832c8c68025d0c6ee099951c7f57864d79854a4979282c4255ef83efc85a311e42a183021ffcddb0e8f5205
      RDS_DB_NAME: development
      RDS_USERNAME: root
      RDS_PASSWORD: root
      RDS_HOSTNAME: rails_db
      RDS_PORT: 3306
      REDIS_HOSTNAME: redis://rails_redis:6379
    volumes:
      - ${PWD}/docker/app/bin:/work/bin:ro
      - ${PWD}/src:/work/app
      - rails-bundle-data:/bundle
    command: sh /work/bin/run.sh
    depends_on:
      - rails_db
      - rails_smtp
      - rails_redis
    links:
      - rails_db
      - rails_smtp
      - rails_redis

  rails_smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

  rails_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "18080:80"
    depends_on:
      - rails_db
    links:
      - rails_db
    environment:
      PMA_HOST: rails_db
      PMA_USER: root
      PMA_PASSWORD: root

  rails_redis:
    image: redis:3.2.11-alpine
    ports:
      - "6379:6379"
    volumes:
       - rails-redis-data:/data

volumes:
  rails-mysql-data:
    driver: local
  rails-bundle-data:
    driver: local
  rails-redis-data:
    driver: local
